spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/userdb}
      auto-index-creation: ${MONGO_AUTO_INDEX:true}
  application:
    name: ${APP_NAME:user-service}

server:
  port: ${SERVER_PORT:8080}

services:
  company-service:
    url: ${COMPANY_SERVICE_URL:http://company-service:8081}
